### ISSUE TITLE
Using this package with spatie media library

### ISSUE THREAD

**Issue by phuclh** [stancl/tenancy-docs#78]
I am using this package with Spatie media library (https://docs.spatie.be/laravel-medialibrary/v8/basic-usage/retrieving-media/)

When I upload an image, it will be added to `storage/{tenant_id}/app/public`. Normally, when I want to return the image URL, I just use: `$mediaItems[0]->getFullUrl()` or `$mediaItems[0]->getUrl()`, but it return an global of storage path:

`http://domain.test/storage/16/conversions/image-medium.jpg`.

Right now, I have to do some string handling to make that above URL turn to:
`http://tenant.domain.test/tenancy/assets/16/conversions/image-medium.jpg`

Are there any ways to make the `getFullUrl` or `getUrl` return the right URL without handle string stuff? Thank you!

**Comment by izshreyansh** [comment]
@kakajansh 's answer did the trick.

But it helps notice that you'll likely have to implement these function: `getTemporaryUrl`, `getPath` from default URL 
Generator class found in `Spatie\MediaLibrary\UrlGenerator`.
[Because that is mandated by abstract class `Spatie\MediaLibrary\UrlGenerator\BaseUrlGenerator`]
